import { ForecastRequestData } from "@/types/forecast";

export const tabColumnSets: Record<string, string[]> = {
  current: [
    "Tarih",
    "Oda",
    "Pax",
    "Yetişkin",
    "Çocuk",
    "Mevcut",
    "Yüzde%",
    "Brut Tutar",
    "Doviz Tutar",
    "TL Gerçek",
  ],
  date: [
    "Tarih",
    "TarihAy",
    "Oda",
    "Pax",
    "Yetişkin",
    "Çocuk",
    "Gelen Oda",
    "Giden Oda",
    "Forecast",
    "Son_Yuzdem",
  ],
  detail: [
    "Tarih",
    "Oda",
    "Pax",
    "Free",
    "Bebek",
    "Yetişkin",
    "Çocuk",
    "Comp Oda",
    "House Use Oda",
    "Info Oda",
    "Pax(P)",
    "Pax(Prm)",
  ],
  waiting: [
    "Tarih",
    "Forecast",
    "Forecast Satılan",
    "Forecast Kalan",
    "Kontenjan Oda",
    "Kontenjan Satılan",
    "Kontenjan Kalan",
    "NoShow",
    "Stop",
  ],
  location: [
    "Tarih",
    "Konum1",
    "Konum1%",
    "Konum2",
    "Konum2%",
    "Konum3",
    "Konum3%",
    "Konum4",
    "Konum4%",
    "Konum5",
    "Konum5%",
    "Konum6",
  ],
  compare: [
    "Tarih",
    "Mevcut",
    "Son Durum",
    "Fark_Yuzde",
    "Yuzde%(Net)",
    "Yuzde%(Sondurum)",
    "Otel Adı",
    "Otel Kodu",
  ],
};

export const defaultForecastRequest: ForecastRequestData = {
  db_Id: 9,
  xRez_Sirket: 9,
  xBas_Tar: "2024-06-01",
  xBit_Tar: "2024-06-10",
  xtip: 1,
  kon1: "ALL",
  kon2: "BB",
  xchkFis_Fazla_otel_10: 0,
  bas_Yil: 2022,
  bit_Yil: 2022,
  fisrci_Kapalioda_10: 0,
  xRez_C_W: "C",
  xSistem_Tarihi: "2024-01-01",
  xAlis_Tarihi: "2024-01-01",
  sistem_Bas1: "2020-01-01",
  sistem_Bit1: "2029-01-01",
  pmdahil_10: 0,
  tip_1: "001",
  xFis_Bela_tutar_10: 0,
  trace_Dus_10: 0,
  cev_01: null,
};
